apiVersion: v1
kind: Service
metadata:
  name: sanic-web-service
  labels:
    app: sanic-web-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: sanic-web-service
